name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: projects/915484313024/locations/global/workloadIdentityPools/my-pool/providers/github
          service_account: gke-workload@praveen-345.iam.gserviceaccount.com

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: praveen-345

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          IMAGE="asia-south1-docker.pkg.dev/praveen-345/argocd-rollout/test-cloud-run"
          docker build -t $IMAGE ./app
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy test-cloud-run \
            --image=asia-south1-docker.pkg.dev/praveen-345/argocd-rollout/test-cloud-run \
            --region=asia-south1 \
            --platform=managed \
            --allow-unauthenticated

