name: Trigger Cloud Build on Python Change

on:
  push:
    branches: [main]
    paths: ['*.py', 'cloudbuild.yaml']

jobs:
  trigger-cloud-build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/915484313024/locations/global/workloadIdentityPools/my-pool/providers/github
          service_account: gke-workload@praveen-345.iam.gserviceaccount.com

      - name: Trigger Cloud Build
        run: gcloud builds submit --config cloudbuild.yaml --project=praveen-345 .
